@echo off
setlocal enabledelayedexpansion
title Naukri Automation - Production Server

echo.
echo  =====================================================
echo       NAUKRI AUTOMATION - PRODUCTION LAUNCHER
echo  =====================================================
echo   Frontend : https://naukri-automation-sagar.web.app
echo  =====================================================
echo.

:: -------------------------------------------------------
:: STEP 1 — Start FastAPI Backend
:: -------------------------------------------------------
echo [1/3] Starting FastAPI Backend on port 8001...
cd /d "%~dp0naukri-automation-api"
start "Backend - FastAPI" cmd /k "call venv\Scripts\activate && python main.py"
cd /d "%~dp0"

echo       Waiting 5 seconds for backend to initialize...
timeout /t 5 /nobreak >nul

:: -------------------------------------------------------
:: STEP 2 — Start Cloudflare Tunnel (write log to file)
:: -------------------------------------------------------
echo [2/3] Starting Cloudflare Tunnel...

set "CLOUDFLARED=C:\Program Files (x86)\cloudflared\cloudflared.exe"
set "TUNNEL_LOG=%TEMP%\cloudflare_tunnel.log"

if not exist "%CLOUDFLARED%" (
    echo [ERROR] cloudflared.exe not found at: %CLOUDFLARED%
    echo         Please reinstall: winget install Cloudflare.cloudflared
    pause
    exit /b 1
)

:: Delete old log
if exist "%TUNNEL_LOG%" del "%TUNNEL_LOG%"

:: Start tunnel in its own window — writes output to log file
start "Tunnel - Cloudflare" cmd /k ""%CLOUDFLARED%" tunnel --url http://localhost:8001 > "%TUNNEL_LOG%" 2>&1"

:: Wait for tunnel URL to appear in the log
echo       Waiting for tunnel URL (up to 30 seconds)...
set "TUNNEL_URL="
set /a attempts=0

:WAIT_FOR_URL
timeout /t 2 /nobreak >nul
set /a attempts+=1

:: Use PowerShell to extract the trycloudflare URL from log
for /f "usebackq delims=" %%U in (`powershell -NoProfile -Command "if (Test-Path '%TUNNEL_LOG%') { Select-String -Path '%TUNNEL_LOG%' -Pattern 'https://.*trycloudflare\.com' | ForEach-Object { $_.Matches[0].Value } | Select-Object -Last 1 }"`) do (
    set "TUNNEL_URL=%%U"
)

if "!TUNNEL_URL!"=="" (
    if !attempts! lss 15 goto WAIT_FOR_URL
    echo.
    echo [WARNING] Could not auto-detect tunnel URL.
    echo           Open the "Tunnel - Cloudflare" window to see the URL.
    echo           Then manually update VITE_API_URL in:
    echo           "%~dp0Naukri Frontend\naukri-frontend\.env.production"
    echo           And run: cd "Naukri Frontend\naukri-frontend" ^&^& npm run build ^&^& firebase deploy --only hosting
    goto SKIP_DEPLOY
)

echo.
echo  +----------------------------------------------------+
echo   Tunnel URL: !TUNNEL_URL!
echo  +----------------------------------------------------+
echo.

:: -------------------------------------------------------
:: STEP 3 — Update .env.production and Redeploy Frontend
:: -------------------------------------------------------
echo [3/3] Updating frontend with new tunnel URL and redeploying...

set "ENV_PROD=%~dp0Naukri Frontend\naukri-frontend\.env.production"

(
    echo # Auto-generated by start_with_tunnel.bat on %DATE% %TIME%
    echo # Cloudflare Tunnel URL ^(changes on each restart^)
    echo VITE_API_URL=!TUNNEL_URL!
) > "%ENV_PROD%"

echo       Building React app for production...
cd /d "%~dp0Naukri Frontend\naukri-frontend"
call npm run build

if %errorlevel% neq 0 (
    echo [ERROR] Build failed! Check errors above.
    pause
    exit /b 1
)

echo       Deploying to Firebase Hosting...
call firebase deploy --only hosting

if %errorlevel% equ 0 (
    echo.
    echo  =====================================================
    echo   SUCCESS! Everything is live.
    echo  =====================================================
    echo.
    echo   Live App   : https://naukri-automation-sagar.web.app
    echo   Tunnel URL : !TUNNEL_URL!
    echo   API Docs   : !TUNNEL_URL!/docs
    echo.
    echo   Share this with your users:
    echo   https://naukri-automation-sagar.web.app
    echo.
    echo   KEEP THE "Tunnel - Cloudflare" WINDOW OPEN!
    echo   Closing it will kill the tunnel and break the app.
    echo  =====================================================
) else (
    echo [ERROR] Firebase deploy failed. Check errors above.
)

:SKIP_DEPLOY
cd /d "%~dp0"
echo.
echo Press any key to exit (backend and tunnel will keep running in their windows)...
pause >nul
